### ISSUE TITLE
failed to convert geojson to geobuf

### ISSUE THREAD

**Issue by hoogw** [mapbox/pygeobuf#28]
in windows, I had try all kinds of way, but still failed. 

In windows command line, 

`python (get into interpreter)

import geobuf
geobuf.encode("city_streets.geojson", "c.pbf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\PYTHON27\lib\site-packages\geobuf-1.1.0-py2.7.egg\geobuf\__init__.py"
, line 8, in encode
    return Encoder().encode(*args)
  File "C:\PYTHON27\lib\site-packages\geobuf-1.1.0-py2.7.egg\geobuf\encode.py",
line 30, in encode
    self.e = pow(10, precision) # multiplier for converting coordinates into int
egers
TypeError: unsupported operand type(s) for ** or pow(): 'int' and 'str'
`

can you show me where I am wrong?

**Comment by sgillies** [comment]
`geobuf.encode("city_streets.geojson", "c.pbf")` is not valid usage. This function takes GeoJSON text as a string and returns a string of protobuf encoded bytes. Please see https://github.com/mapbox/pygeobuf#usage for the correct usage.

**Comment by hoogw** [comment]
what is python version requirement?

I have python 27 installed. 

I have read usage doc, but can't figure out how to do it in windows command line. 
Should I type python to get into interpreter? 
I already installed geobuf by run setup.py successfully.

this is error I got.  Please give me a hint, where is wrong?
.......
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on wi
n32
Type "help", "copyright", "credits" or "license" for more information.
>>> geobuf encode <city_streets.geojson> city_streets.pbf
  File "<stdin>", line 1
    geobuf encode <city_streets.geojson> city_streets.pbf
                ^
SyntaxError: invalid syntax
>>>

**Comment by sgillies** [comment]
I haven't used Windows in a long time, and am not an expert, but if you installed geobuf there should be a geobuf script in your Python Scripts directory and if you configure your Windows environment correctly, you will be able to run it on the Windows command line. I won't be able to help you with that because I do not have a Windows computer and am not familiar with the newest version. Check the Windows FAQ at python.org

https://docs.python.org/2/faq/windows.html

and also check Stack Overflow for help. I found what looks to be some thorough advice here:

http://stackoverflow.com/a/13533958

Good luck!
